name: Validate Protobuf

on:
  push:
    branches: [ main ]
    paths:
      - 'icecap/**/*.proto'
  pull_request:
    branches: [ main ]
    paths:
      - 'icecap/**/*.proto'

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          format: true
          lint: true

